version: '3.6'

services:
  api:
    build:
      context: api
    ports:
      - "3000:3030"
    depends_on:
      - db
  app:
    build:
      context: app
    working_dir: /app
    command: "yarn serve"
    ports:
      - "8080:8080"
    depends_on:
      - api
  test:
    image: nginx:1.21
    ports:
      - "8080:80"
    volumes:
      - ./app/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - db