version: '3.6'

services:
  api:
    build:
      context: api
    ports:
      - "3000:3030"
  vue:
    build:
      context: app
    volumes:
      - ./app:/app
      - node_modules_volume:/app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "8081:8080"
    working_dir: /app
  app:
    image: nginx:1.21
    ports:
      - "8080:80"
    volumes:
      - ./app/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  node_modules_volume:
