version: '3.6'

services:
  api:
    build:
      context: api
    ports:
      - "3000:3030"
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
    depends_on:
      - api