version: '3.6'

services:
  api:
    build:
      context: api
    ports:
      - "3000:3030"
  app:
    build:
      context: app
    stdin_open: true
    tty: true
    working_dir: /app
    command: "yarn serve"
    ports:
      - "8080:8080"
    depends_on:
      - api
  test:
    image: nginx:1.21
    ports:
      - "8080:80"
    volumes:
      - ./app/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
